### ISSUE TITLE
Barras do Pong

### ISSUE THREAD

**Issue by AndreySchemel** [lucasferreira97/ProjetoProg3#11]
Adicionar as barras de cada jogador, podendo ser uma do computador e outra do Player, ou 2 Players.

Primeiramente com o Computador, com o decorrer do trabalho iremos fazer para cada jogador, usando as teclas A S W D e setas.

As barras serão desenvolvidas com JavaScript.
Que talvez serão personalizadas, como opção de mudar de cor, tamanho, e outras opções.

**Comment by lucasferreira97** [comment]
no momento foram adicionadas somente as barras de player 1 e 2
