### ISSUE TITLE
Fazer o básico - Canvas

### ISSUE THREAD

**Issue by lucasferreira97** [lucasferreira97/ProjetoProg3#2]

**Comment by AndreySchemel** [comment]
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="600" height="400" style="border:3px solid #000000;">

(Width e Height: Poderá mudar de acordo com a página e outras funções)
<script>

var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.fillStyle = "black";
ctx.fillRect(0, 0, 600, 400);

</script>

</body>
</html>
