### ISSUE TITLE
Adicionar Script para a bolinha

### ISSUE THREAD

**Issue by lucasferreira97** [lucasferreira97/ProjetoProg3#3]

**Comment by LeosBSI** [comment]
<script>
var canvas = document.getElementById("mycanvas");
var ctx = canvas.getContext("2d");

var teclas = {};
var bola = {
	x: canvas.width / 2 - 15,
	y: canvas.height / 2 - 15,
	altura : 30,
	largura : 30,
	dirx : -1,
	diry : 1,
	mod : 0,
	speed : 50,
}

var esquerda = {
	x : 10,
	y : canvas.height / 2 - 60;
	altura : 120,
	largura : 30,
	score : 0,
	speed : 15
};
var direita = {
	x : 560,
	y : canvas.height / 2 - 60,
	altura : 120,
	largura : 30,
	score : 0,
	speed : 15,
};

function desenha() {
	ctx.fillStyle = "white";
	ctx.fillRect(esquerda.x, esquerda.y, esquerda.largura, esquerda.altura);
	ctx.fillRect(direita.x, direita.y, direita.largura, direita.altura);
	ctx.fillRect(bola.x, bola.y, bola.largura, bola.altura);
}

</script>

**Comment by LeosBSI** [comment]
**FALTA TERMINAR**
<script>
var canvas = document.getElementById("mycanvas");
var ctx = canvas.getContext("2d");

var teclas = {};
var bola = {
	x: canvas.width / 2 - 15,
	y: canvas.height / 2 - 15,
	altura : 30,
	largura : 30,
	dirx : -1,
	diry : 1,
	mod : 0,
	speed : 50,
}

var esquerda = {
	x : 10,
	y : canvas.height / 2 - 60;
	altura : 120,
	largura : 30,
	score : 0,
	speed : 15
};

var direita = {
	x : 560,
	y : canvas.height / 2 - 60,
	altura : 120,
	largura : 30,
	score : 0,
	speed : 15,
};

function desenha() {
	ctx.fillStyle = "white";
	ctx.fillRect(esquerda.x, esquerda.y, esquerda.largura, esquerda.altura);
	ctx.fillRect(direita.x, direita.y, direita.largura, direita.altura);
	ctx.fillRect(bola.x, bola.y, bola.largura, bola.altura);
}

</script>
